import type { BlogPost } from "./blog.types";
export const initialPosts: BlogPost[] = [
  {
    slug: "season-6",
    title: "Season 6 está no ar",
    category: "Atualizações",
    excerpt: "Confira a progressão, os eventos e o mercado da nova temporada.",
    body: "A Season 6 está aberta. Comece em Lorencia, prepare seu personagem e encontre sua guilda.\n\nExperiência ×3, drop ×3 e limite de 250 resets. Os eventos clássicos fazem parte da rotina do servidor.\n\nO marketplace permite negociar itens, joias e Nightmare Coins. Organize seu cofre antes de entrar nas disputas.\n\nEste anúncio é demonstrativo. Compartilhe nos comentários o que você pretende conquistar nesta temporada.",
    image: "/images/mu/dk.jpg",
    author: "Equipe Nightmare",
    date: "2026-10-04T15:00:00-03:00",
    likes: [],
    comments: [],
  },
  {
    slug: "castle-siege",
    title: "Prepare sua guilda para o Castle Siege",
    category: "Eventos",
    excerpt: "Organize seu grupo e dispute o controle do castelo.",
    body: "O Castle Siege reúne guildas em uma disputa pelo castelo. Prepare a composição da equipe e combine funções antes do evento.\n\nConsulte a agenda do servidor para conferir o horário. Qual guilda vai levar o título?",
    image: "/images/mu/dl.jpg",
    author: "Equipe Nightmare",
    date: "2026-10-03T18:00:00-03:00",
    likes: [],
    comments: [],
  },
  {
    slug: "recompensas-bugs",
    title: "Reportes de bugs podem render recompensas",
    category: "Servidor",
    excerpt: "Saiba como registrar uma falha e ajudar a melhorar o servidor.",
    body: "Encontrou um bug? Registre os passos para reproduzir a falha, o resultado esperado e o impacto no jogo.\n\nReportes válidos podem receber recompensas após análise da equipe. Não explore a falha nem divulgue dados sensíveis.\n\nUse a página Reportar bug para enviar seu relato. No protótipo, o protocolo fica salvo neste navegador.",
    image: "/images/mu/mg.jpg",
    author: "Equipe Nightmare",
    date: "2026-10-02T12:00:00-03:00",
    likes: [],
    comments: [],
  },
];
